"""empty message

Revision ID: 517148f80a6b
Revises: 3c697ee1e1a7
Create Date: 2019-08-07 16:50:38.728571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517148f80a6b'
down_revision = '3c697ee1e1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
